server:
  port: 9001

spring:
  kafka:
    bootstrap-servers: localhost:9092
    application-id: client-streams-app
    consumer:
      group-id: clientService
    properties:
      schema.registry.url: http://localhost:8085
      specific.avro.reader: true
