server:
  port: 9002

spring:
  kafka:
    producer:
      properties:
        schema.registry.url: http://localhost:8085
      bootstrap-servers: localhost:9092
      group-id: client_group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer